FROM mcr.microsoft.com/vscode/devcontainers/base:debian-11

ENV DOCKER_BUILDKIT=1

############################################################################
# ARG
############################################################################

ARG USERNAME=vscode
ARG TARGETARCH
ARG TARGETPLATFORM

############################################################################
# DOCKER BUILDX FLAG
############################################################################
    
ENV BUILDX_NO_DEFAULT_ATTESTATIONS="1"


###########################################################################
# MISC (MIGHT BE IMPORTANT)
###########################################################################

RUN apt-get install xz-utils -y
RUN apt-get install libc6-dev -y


# ############################################################################
# # PERSISTENT CMD HISTORY
# ############################################################################

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.zsh_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.zsh_history \
    && chown -R $USERNAME /commandhistory \
    && echo $SNIPPET >>"/home/$USERNAME/.zshrc"


############################################################################
# INSTALL DENO
############################################################################

USER root

ENV DENO_VERSION=v2.0.3

ENV DENO_INSTALL=/deno
RUN mkdir -p /deno && curl -fsSL https://deno.land/x/install/install.sh | sh -s ${DENO_VERSION} && chown -R vscode /deno
ENV PATH=${DENO_INSTALL}/bin:${PATH}
ENV DENO_DIR=${DENO_INSTALL}/.cache/deno

USER vscode

############################################################################
# INSTALL DENO
############################################################################


RUN git clone https://github.com/ghostmind-dev/run.git ${HOME}/run
RUN deno install --allow-all --force --global --name run ${HOME}/run/run/bin/cmd.ts
ENV PATH="/home/vscode/.deno/bin:${PATH}"


############################################################################
# INSTALL GCLOUD
############################################################################

USER root

ENV GCLOUD_VERSION=405.0.0


RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ARCHITECTURE=x86_64; else ARCHITECTURE=arm; fi  \
    && cd /tmp  \
    && curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${GCLOUD_VERSION}-linux-${ARCHITECTURE}.tar.gz   \
    && tar -xf google-cloud-cli-${GCLOUD_VERSION}-linux-${ARCHITECTURE}.tar.gz    \
    && /tmp/google-cloud-sdk/install.sh  \
    && mv /tmp/google-cloud-sdk/ /usr/local/lib 

ENV PATH="$PATH:/usr/local/lib/google-cloud-sdk/bin"

RUN gcloud components install gke-gcloud-auth-plugin
RUN gcloud components install beta

ENV GOOGLE_APPLICATION_CREDENTIALS="/tmp/gsa_key.json"



############################################################################
# HASHICORP VAULT
############################################################################

USER root

RUN apt update
RUN apt install -y gpg
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt update
RUN apt install vault -y


#############################################################################
# INSTALL NODEJS
#############################################################################

ENV NODE_MAJOR=20

RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install nodejs -y
ENV NODE_OPTION="--openssl-legacy-provider"



############################################################################
# NPM SETUP
############################################################################

USER vscode
RUN mkdir -p /home/vscode/.npm-global/lib
ENV NPM_CONFIG_PREFIX=/home/vscode/.npm-global
ENV PATH=$NPM_CONFIG_PREFIX/bin:$PATH
ENV PATH="/home/vscode/.npm-global/bin:${PATH}"

############################################################################
# INSTALL GLOBAL NPM PACKAGES
############################################################################

RUN npm --global install zx@8.1.1
RUN npm --global install npm-run-all@4.1.5
RUN npm --global install nodemon@3.1.1
RUN npm --global install @anthropic-ai/claude-code
RUN npm --global install @devcontainers/cli


############################################################################
# INSTALL GO
############################################################################

USER root
ENV GO_VERSION=1.21.2

RUN wget https://golang.org/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-${TARGETARCH}.tar.gz
ENV PATH="$PATH:/usr/local/go/bin"


# ############################################################################
# # INSTALL ACT
# ############################################################################

ENV ACT_VERSION=0.2.61

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ARCHITECTURE=x86_64; else ARCHITECTURE=arm64; fi \
    && cd /tmp \
    && wget https://github.com/nektos/act/releases/download/v${ACT_VERSION}/act_Linux_${ARCHITECTURE}.tar.gz \
    && tar -xvf act_Linux_${ARCHITECTURE}.tar.gz \
    && mv act /usr/local/bin/act

############################################################################
# INSTALL TERRAFORM
############################################################################

ENV TERRAFORM_VERSION=1.6.0

RUN cd /tmp \
    && wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip -d /usr/bin
   


############################################################################
# INSTALL HASURA
############################################################################

RUN curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash


############################################################################
# CLOUDFLARED
############################################################################

RUN sudo mkdir -p --mode=0755 /usr/share/keyrings
RUN curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/cloudflared.list
RUN apt-get update && sudo apt-get install cloudflared

############################################################################
# PYTHON CONFIG
############################################################################


RUN sudo apt-get update && sudo apt-get install -y \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    python3-pip \
    python3-openssl \
    git

USER vscode

RUN curl https://pyenv.run | bash

# Set environment variables for pyenv
ENV PATH="/home/vscode/.pyenv/bin:/home/vscode/.pyenv/shims:${PATH}"

# RUN pyenv install 3.12.5
RUN pyenv install 3.9.7
RUN pyenv global 3.9.7



############################################################################
# INSTALL CURL
############################################################################

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

############################################################################
# INSTALL POSTGRESQL CLIENT
############################################################################

USER root

RUN apt-get install -y postgresql-client

############################################################################
# SET USER
############################################################################

USER vscode


# ############################################################################
# # THE END
# ############################################################################